version: 2

sources:
  - name: raw
    description: "Исходные данные из источника"
    schema: stage
    tables:
      - name: accounting_balance_form_1
        description: "Исходная таблица с данными из файла 'form_1.xlsx', загруженная в stage"
        identifier: russian_Форма_1_6_месяцев_2025_год_xls_rzdm-dev-data-lake
        columns:
          - name: asset_id
            description: "Идентификатор актива"
          - name: org_id
            description: "Идентификатор организации"
          - name: ind_id
            description: "Идентификатор показателя"
          - name: eat_id
            description: "Идентификатор вида экономической деятельности"
          - name: unit_id
            description: "Идентификатор единицы измерения"
          - name: discr_id
            description: "Идентификатор дискретности"
          - name: fct_id
            description: "Идентификатор факта"
          - name: mcrreg_id
            description: "Идентификатор макрорегиона"

