name: 'template_1'
version: '1.0.0'
config-version: 2

profile: 'proekt_shablon_1'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  template_1:
    +materialized: view
    +post-hook:
      - "DROP TABLE IF EXISTS {{ this.schema }}.{{ this.identifier }}__dbt_backup"
    staging:
      +materialized: table
      +schema: stage
    rdv:
      +schema: unverified_rdv
      hubs:
        +materialized: table
      links:
        +materialized: table
      sats:
        +materialized: table
    bdv:
      +schema: unverified_bdv
      hubs:
        +tags: ['bdv']
      links:
        +tags: ['bdv']
      sats:
        +tags: ['bdv']

vars:
  source_system: 'excel_forms'
  source_table_name: 'stage.form_1'

