name: 'xlsx_dbt'
version: '1.0.0'
config-version: 2

profile: 'xlsx_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  xlsx_dbt:
    staging:
      +materialized: table
      +schema: staging
    rdv:
      hubs:
        +materialized: table
        +schema: financial_rdv
      links:
        +materialized: table
        +schema: financial_rdv
      sats:
        +materialized: table
        +schema: financial_rdv
    bdv:
      hubs:
        +materialized: table
        +schema: main_bdv
      links:
        +materialized: table
        +schema: main_bdv
      sats:
        +materialized: table
        +schema: main_bdv

vars:
  source_system: '1c'

# on-run-start:
#   - "{{ cleanup_temp_tables() }}"

