{{
  config(
    materialized='table',
    table_type='PRIMARY',
    keys=['contractors_hk'],
    buckets=3,
    properties={
      'replication_num': '1'
    },
    pre_hook="SET @len_items_stg_contractors = (select max(json_length(parse_json(`values`) -> '$[0].Items')) from iceberg.rzdm.stg_contractors);"
  )
}}


WITH numbers AS (
    SELECT generate_series as n FROM table(generate_series(0, @len_items_stg_contractors, 1)) 
)
SELECT 
	UUID() as contractors_hk,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].UID')) AS VARCHAR(100)) AS uid,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].GUID')) AS VARCHAR(100)) AS guid,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].UIDSearchString')) AS VARCHAR(100)) AS uid_search_string,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_AdresMezhdunarodnyy')) AS VARCHAR(250)) AS rc_adres_mezhdunarodnyy,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_VidGosudarstvennogoOrgana')) AS VARCHAR(250)) AS rc_vid_gosudarstvennogo_organa,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_VidKontragentaDlyaVGO')) AS VARCHAR(250)) AS rc_vid_kontragenta_dlya_vgo,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_GorodStranaMezhdunarodnyy')) AS VARCHAR(250)) AS rc_gorod_strana_mezhdunarodnyy,
    CASE WHEN CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_GosudarstvennyyOrgan')) AS VARCHAR(10)) = 'true' THEN 1 ELSE 0 END AS rc_gosudarstvennyy_organ,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_GruppaKontragenta')) AS VARCHAR(250)) AS rc_gruppa_kontragenta,
    str_to_date(CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_DataPostanovkiNaUchetVNalogovoy')) AS VARCHAR(250)), '%Y-%m-%dT%H:%i:%s') AS rc_data_postanovki_na_uchet_v_nalogovoy,
    str_to_date(CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_DataRozhdeniya')) AS VARCHAR(250)), '%Y-%m-%dT%H:%i:%s') AS rc_data_rozhdeniya,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_DULNomer')) AS VARCHAR(250)) AS rc_dul_nomer,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_DULSeriya')) AS VARCHAR(250)) AS rc_dul_seriya,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_Imya')) AS VARCHAR(250)) AS rc_imya,
    CASE WHEN CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_IndividualnyyPredprinimatel')) AS VARCHAR(10)) = 'true' THEN 1 ELSE 0 END AS rc_individualnyy_predprinimatel,
    CASE WHEN CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_IspolzovatProgrammuZakupok')) AS VARCHAR(10)) = 'true' THEN 1 ELSE 0 END AS rc_ispolzovat_programmu_zakupok,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_KanalProdazh')) AS VARCHAR(250)) AS rc_kanal_prodazh,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_KodGosudarstvennogoOrgana')) AS VARCHAR(250)) AS rc_kod_gosudarstvennogo_organa,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_KodOKVED')) AS VARCHAR(250)) AS rc_kod_okved,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_KodOKVED2')) AS VARCHAR(250)) AS rc_kod_okved2,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_KodOKFS')) AS VARCHAR(250)) AS rc_kod_okfs,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_KodPoOKTMO')) AS VARCHAR(250)) AS rc_kod_po_oktmo,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_OsnovnoeKontaktnoeLitso')) AS VARCHAR(250)) AS rc_osnovnoe_kontaktnoe_litso,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_OsnovnoeKontaktnoeLitsoVIFNS')) AS VARCHAR(250)) AS rc_osnovnoe_kontaktnoe_litso_vifns,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_OsnovnoyBankovskiySchet')) AS VARCHAR(250)) AS rc_osnovnoy_bankovskiy_schet,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_Otchestvo')) AS VARCHAR(250)) AS rc_otch,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_PodrazdeleniePoOrgShtatnoyStrukture')) AS VARCHAR(250)) AS rc_podrazdelenie_po_org_shtatnoy_strukture,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_PodrazdeleniePoUpravlencheskoyStrukture')) AS VARCHAR(250)) AS rc_podrazdelenie_po_upravlencheskoy_strukture,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_Pol')) AS VARCHAR(250)) AS rc_pol,
    CASE WHEN CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_PriznakMeditsinskoyOrganizatsii')) AS VARCHAR(10)) = 'true' THEN 1 ELSE 0 END AS rc_priznik_meditsinskoy_organizatsii,
    CASE WHEN CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_Samozanyatyy')) AS VARCHAR(10)) = 'true' THEN 1 ELSE 0 END AS rc_samozanyatyy,
    str_to_date(CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_SvidetelstvoDataVydachi')) AS VARCHAR(250)), '%Y-%m-%dT%H:%i:%s') AS rc_svidetelstvo_data_vydachi,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_SvidetelstvoSeriyaNomer')) AS VARCHAR(250)) AS rc_svidetelstvo_seriya_nomer,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_SNILS')) AS VARCHAR(250)) AS rc_snils,
    CASE WHEN CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_SubektMalogoIliSrednegoPredprinimatelstvaUKh')) AS VARCHAR(10)) = 'true' THEN 1 ELSE 0 END AS rc_subekt_maloго_или_среднего_предпринимательства_ух,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_Familiya')) AS VARCHAR(250)) AS rc_familiya,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_FIOIDolzhnostRukovoditelya')) AS VARCHAR(250)) AS rc_fio_dolzhnost_rukovoditelya,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_FIOIDolzhnostRukovoditelyaVRoditelnomPadezhe')) AS VARCHAR(250)) AS rc_fio_dolzhnost_rukovoditelya_v_roditelnom_padezhe,
    CASE WHEN CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_FormaUchastiyaVKapitale')) AS VARCHAR(10)) = 'true' THEN 1 ELSE 0 END AS rc_forma_uchastiya_v_kapitale,
    CASE WHEN CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_EtoBank')) AS VARCHAR(10)) = 'true' THEN 1 ELSE 0 END AS rc_eto_bank,
    CASE WHEN CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_EtoStrakhovayaKompaniya')) AS VARCHAR(10)) = 'true' THEN 1 ELSE 0 END AS rc_eto_strakhovaya_kompaniya,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].rc_YuridicheskoeFizicheskoeLitso')) AS VARCHAR(250)) AS rc_yuridicheskoe_fizicheskoe_litso,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].GolovnoyKontragent')) AS VARCHAR(250)) AS golovnoy_kontragent,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].DokumentUdostoveryayushchiyLichnost')) AS VARCHAR(250)) AS dokument_udostoveryayushchiy_lichnost,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].Identifikator')) AS VARCHAR(250)) AS identifikator,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].INN')) AS VARCHAR(250)) AS inn,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].KodOKOPF')) AS VARCHAR(250)) AS kod_okopf,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].KodPoOKPO')) AS VARCHAR(250)) AS kod_po_okpo,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].Kommentariy')) AS VARCHAR(250)) AS kommentariy,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].KPP')) AS VARCHAR(250)) AS kpp,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].MezhdunarodnoeNaimenovanie')) AS VARCHAR(250)) AS mezhdunarodnoe_naimenovanie,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].NaborSvoystv')) AS VARCHAR(250)) AS nabor_svoystv,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].NaimenovanieOKOPF')) AS VARCHAR(250)) AS naimenovanie_okopf,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].NalogovyyNomer')) AS VARCHAR(250)) AS nalogovyy_nomer,
    CASE WHEN CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].Nerezident')) AS VARCHAR(10)) = 'true' THEN 1 ELSE 0 END AS nerezident,
    CASE WHEN CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].ObosoblennoePodrazdelenie')) AS VARCHAR(10)) = 'true' THEN 1 ELSE 0 END AS obosoblennoe_podrazdelenie,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].OGRN')) AS VARCHAR(250)) AS ogrn,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].OKDP')) AS VARCHAR(250)) AS okdp,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].Opisanie')) AS VARCHAR(250)) AS opisanie,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].OrganizatsionnayaEdinitsa')) AS VARCHAR(250)) AS organizatsionnaya_edinitsa,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].OrganizatsionnoPravovayaForma')) AS VARCHAR(250)) AS organizatsionno_pravovaya_forma,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].Partner')) AS VARCHAR(250)) AS partner,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].PolnoeNaimenovanie')) AS VARCHAR(250)) AS polnoe_naimenovanie,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].PriznakIspolzovaniya')) AS VARCHAR(250)) AS priznik_ispolzovaniya,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].RegistratsionnyyNomerNerezidenta')) AS VARCHAR(250)) AS registratsionnyy_nomer_nerezidenta,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].SokrashchennoeNaimenovanie')) AS VARCHAR(250)) AS sokrashchennoe_naimenovanie,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].StranaRegistratsii')) AS VARCHAR(250)) AS strana_registratsii,
    CASE WHEN CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].UdalitZapisNeNormalizuema')) AS VARCHAR(10)) = 'true' THEN 1 ELSE 0 END AS udalit_zapis_ne_normalizuema,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].UdalitTipPozitsii')) AS VARCHAR(250)) AS udalit_tip_pozitsii,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].UdalitEtalonnayaPozitsiya')) AS VARCHAR(250)) AS udalit_etalonnaya_pozitsiya,
    CASE WHEN CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].UdalitEtoMaket')) AS VARCHAR(10)) = 'true' THEN 1 ELSE 0 END AS udalit_eto_maket,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].UdalitEtoZapisi')) AS VARCHAR(250)) AS udalit_eto_zapisi,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].YurFizLitso')) AS VARCHAR(250)) AS yur_fiz_litso,
    CAST(json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, '].OsnovnoyBankovskiySchet')) AS VARCHAR(250)) AS osnovnoy_bankovskiy_schet,
    src.src_sys_id,
    CURRENT_TIMESTAMP as load_dttm
FROM iceberg.rzdm.stg_contractors AS src
CROSS JOIN numbers AS n
WHERE src.`values` IS NOT NULL
  AND json_query(parse_json(src.`values`), CONCAT('$[0].Items[', n.n, ']')) IS NOT NULL;